spring:
  application:
    name: woohakdong-server

  datasource:
    url: jdbc:mysql://localhost:3306/woohakdong?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: woohakdong
    password: woohakdong123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      s3:
        bucket-name: ${AWS_S3_BUCKET_NAME:woohakdong_dummy_bucket}

jwt:
  secret: ${JWT_SECRET:woohakdongwoohakdongwoohakdong1234}

cookie:
  secure: false  # 로컬 환경에서는 HTTP 허용
  same-site: None  # localhost 간 cross-origin 허용
  domain: .woohakdong.com


firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH:firebase-service-account.json}

logging:
  level:
    com.woohakdong.framework.filter.RequestLoggingFilter: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
